export const FETCH_REPORTS_START = 'FETCH_REPORTS_START';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAIL = 'FETCH_REPORTS_FAIL';

export const CREATE_REPORT_START = 'CREATE_REPORT_START';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';
export const CREATE_REPORT_INIT = 'CREATE_REPORT_INIT';

export const FETCH_REPORT_IMAGES_START = 'FETCH_REPORT_IMAGES_START';
export const FETCH_REPORT_IMAGES_SUCCESS = 'FETCH_REPORT_IMAGES_SUCCESS';
export const FETCH_REPORT_IMAGES_FAIL = 'FETCH_REPORT_IMAGES_FAIL';

export const CREATE_REPORT_IMAGE_START = 'CREATE_REPORT_IMAGE_START';
export const CREATE_REPORT_IMAGE_SUCCESS = 'CREATE_REPORT_IMAGE_SUCCESS';
export const CREATE_REPORT_IMAGE_FAIL = 'CREATE_REPORT_IMAGE_FAIL';
export const CREATE_REPORT_IMAGE_INIT = 'CREATE_REPORT_IMAGE_INIT';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_INIT = 'UPDATE_PROFILE_INIT';